version: '3'

services:
  app:
    build: .
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app/back

  database:
    container_name: 'database_sql'
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports: 
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_USER=root
      - MYSQL_PASSWORD=docker
      - MYSQL_DATABASE=task_db
      - HOSTNAME=localhost
      - SECRET_KEY=hulkEsmaga
      - PORT=3000
      - TZ=America/Sao_Paulo